### ISSUE TITLE
Referenced classes were moved in recent kafka versions

### ISSUE THREAD

**Issue by spike83** [confluentinc/confluent-oauth-extensions#1]
I faced some issues using this library with kafka 3.6.1. It seems some classes were moved in the kafka packages. So this is not working anymore.

Is this the current implementation using azure MI tokens or is there a better way?
Is there a pre-built jar somewhere?

**Comment by spike83** [comment]
@javabrett thanks for merging. The question remains if there is a release we can download? Do you plan to have one at some point? Or is this something every customer needs to build separately?

**Comment by javabrett** [comment]
@spike83 I'm checking with the team if/how we can do a binary release.
